# Generated by Django 6.0 on 2025-12-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavBarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, default='static/main/images/navbar_logo/default_logo.png', null=True, upload_to='static/main/images/navbar_logo')),
            ],
        ),
    ]
