# Generated by Django 6.0 on 2025-12-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('primary_phone', models.CharField(max_length=20)),
                ('secondary_phone', models.CharField(blank=True, max_length=20)),
                ('google_map_embed_url', models.TextField(help_text='Paste the Google Maps embed URL here')),
            ],
        ),
        migrations.AlterField(
            model_name='navbaritem',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='navbar_logo/'),
        ),
    ]
