# Generated by Django 6.0 on 2026-01-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_blogpost_image_url_blogpost_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='summary',
        ),
    ]
