# Generated by Django 6.0 on 2026-01-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_blogpost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('embedded_url', models.TextField(help_text='Paste the YouTube link, TikTok link, or full Embed code here')),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=10)),
                ('processed_id', models.CharField(editable=False, max_length=255)),
            ],
        ),
    ]
