# Generated by Django 6.0 on 2026-01-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_videocontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocontent',
            name='title',
        ),
    ]
