# Generated by Django 6.0 on 2026-01-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_videocontent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
