# Generated by Django 6.0 on 2026-01-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_videocontent_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('alt_text', models.CharField(default='Gallery Image', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
