# Generated by Django 6.0 on 2026-01-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOTitleAndMetaDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('service', 'Services'), ('gallery', 'Gallery'), ('blog', 'Blog')], help_text='Select the page this SEO data belongs to.', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Include Title from 50 to 65 characters.', max_length=100)),
                ('meta_description', models.TextField(help_text='Include Meta Description from 70 to 150 characters.')),
            ],
            options={
                'verbose_name': 'SEO Setting',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
    ]
