# Generated by Django 6.0 on 2026-01-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_seotitleandmetadescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocontent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='videocontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
