# Generated by Django 6.0 on 2026-01-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_videocontent_options_videocontent_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Followed Up / Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedRecord',
            fields=[
            ],
            options={
                'verbose_name': 'Followed-up Record',
                'verbose_name_plural': 'Followed-up Records',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.appointment',),
        ),
        migrations.CreateModel(
            name='NewRequest',
            fields=[
            ],
            options={
                'verbose_name': 'New Request',
                'verbose_name_plural': 'New Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.appointment',),
        ),
    ]
