# Generated by Django 6.0 on 2026-01-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_appointment_completedrecord_newrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideshowImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slideshow/')),
                ('alt_text', models.CharField(blank=True, help_text='Used for SEO and screen readers', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slideshow Image',
                'verbose_name_plural': 'Slideshow Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
