# Generated by Django 6.0 on 2026-01-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_slideshowimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
